apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bw1tea984-go 
  janus-idp.io/tekton: bw1tea984-go
  backstage.io/kubernetes-id: bw1tea984-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bw1tea984-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml