apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bw1tea984-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bw1tea984-go 
  name: bw1tea984-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bw1tea984-go 
